parameters:

services:
    axioma.listener.translator:
        class: Axioma\Bundle\TranslatorBundle\Listener\AxiomaTranslatorRequestListener
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }